import PostBackground from "../../assets/images/common/studyExampleImage.png";

export const dummyStudyPosts = [
  {
    postId: 1,
    postTitle: "제목입니다",
    postContent:
      "설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명 설명입니다 설명설명 설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명 설명입니다 설명설명 설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명 설명입니다 설명설명 설명설명 설명설명입니다",
    postBackgroundImg: PostBackground,
    postAgo: "1시간 전",
    postDday: 5,
    postRecruiter: "N",
    postState: "모집중",
    postApplicant: "n",
  },
  {
    postId: 2,
    postTitle: "제목입니다",
    postContent:
      "설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명 설명입니다 설명설명 설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명 설명입니다 설명설명 설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명 설명입니다 설명설명 설명설명 설명설명입니다",
    postBackgroundImg: PostBackground,
    postAgo: "1시간 전",
    postDday: 5,
    postRecruiter: "N",
    postState: "모집중",
    postApplicant: "n",
  },
  {
    postId: 3,
    postTitle: "제목입니다",
    postContent:
      "설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명 설명입니다 설명설명 설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명 설명입니다 설명설명 설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명 설명입니다 설명설명 설명설명 설명설명입니다",
    postBackgroundImg: PostBackground,
    postAgo: "1시간 전",
    postDday: 5,
    postRecruiter: "N",
    postState: "모집중",
    postApplicant: "n",
  },
  {
    postId: 4,
    postTitle: "제목입니다",
    postContent:
      "설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명 설명입니다 설명설명 설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명 설명입니다 설명설명 설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명 설명입니다 설명설명 설명설명 설명설명입니다",
    postBackgroundImg: PostBackground,
    postAgo: "1시간 전",
    postDday: 5,
    postRecruiter: "N",
    postState: "모집중",
    postApplicant: "n",
  },
  {
    postId: 5,
    postTitle: "제목입니다",
    postContent:
      "설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명 설명입니다 설명설명 설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명 설명입니다 설명설명 설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명 설명입니다 설명설명 설명설명 설명설명입니다",
    postBackgroundImg: PostBackground,
    postAgo: "1시간 전",
    postDday: 5,
    postRecruiter: "N",
    postState: "모집중",
    postApplicant: "n",
  },
  {
    postId: 6,
    postTitle: "제목입니다",
    postContent:
      "설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명 설명입니다 설명설명 설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명 설명입니다 설명설명 설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명 설명입니다 설명설명 설명설명 설명설명입니다",
    postBackgroundImg: PostBackground,
    postAgo: "1시간 전",
    postDday: 5,
    postRecruiter: "N",
    postState: "모집중",
    postApplicant: "n",
  },
  {
    postId: 7,
    postTitle: "제목입니다",
    postContent:
      "설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명 설명입니다 설명설명 설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명 설명입니다 설명설명 설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명 설명입니다 설명설명 설명설명 설명설명입니다",
    postBackgroundImg: PostBackground,
    postAgo: "1시간 전",
    postDday: 5,
    postRecruiter: "N",
    postState: "모집중",
    postApplicant: "n",
  },
  {
    postId: 8,
    postTitle: "제목입니다",
    postContent:
      "설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명 설명입니다 설명설명 설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명 설명입니다 설명설명 설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명 설명입니다 설명설명 설명설명 설명설명입니다",
    postBackgroundImg: PostBackground,
    postAgo: "1시간 전",
    postDday: 5,
    postRecruiter: "N",
    postState: "모집중",
    postApplicant: "n",
  },
  {
    postId: 9,
    postTitle: "제목입니다",
    postContent:
      "설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명 설명입니다 설명설명 설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명 설명입니다 설명설명 설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명 설명입니다 설명설명 설명설명 설명설명입니다",
    postBackgroundImg: PostBackground,
    postAgo: "1시간 전",
    postDday: 5,
    postRecruiter: "N",
    postState: "모집중",
    postApplicant: "n",
  },
  {
    postId: 10,
    postTitle: "제목입니다",
    postContent:
      "설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명 설명입니다 설명설명 설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명 설명입니다 설명설명 설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명 설명입니다 설명설명 설명설명 설명설명입니다",
    postBackgroundImg: PostBackground,
    postAgo: "1시간 전",
    postDday: 5,
    postRecruiter: "N",
    postState: "모집중",
    postApplicant: "n",
  },
  {
    postId: 11,
    postTitle: "제목입니다",
    postContent:
      "설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명 설명입니다 설명설명 설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명 설명입니다 설명설명 설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명 설명입니다 설명설명 설명설명 설명설명입니다",
    postBackgroundImg: PostBackground,
    postAgo: "1시간 전",
    postDday: 5,
    postRecruiter: "N",
    postState: "모집중",
    postApplicant: "n",
  },
  {
    postId: 12,
    postTitle: "제목입니다",
    postContent:
      "설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명 설명입니다 설명설명 설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명 설명입니다 설명설명 설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명 설명입니다 설명설명 설명설명 설명설명입니다",
    postBackgroundImg: PostBackground,
    postAgo: "1시간 전",
    postDday: 5,
    postRecruiter: "N",
    postState: "모집중",
    postApplicant: "n",
  },
  {
    postId: 13,
    postTitle: "제목입니다",
    postContent:
      "설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명 설명입니다 설명설명 설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명 설명입니다 설명설명 설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명 설명입니다 설명설명 설명설명 설명설명입니다",
    postBackgroundImg: PostBackground,
    postAgo: "1시간 전",
    postDday: 5,
    postRecruiter: "N",
    postState: "모집중",
    postApplicant: "n",
  },
];
