import UserProfileImg from "../../../assets/images/community/userProfile.png";
import PostBackground from "../../../assets/images/common/communityExampleImage.png";

export const dummyBlogPosts = [
  {
    postId: 1,
    postTitle: "블로그 제목",
    postContent:
      "설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명",
    postBackgroundImg: PostBackground,
    postUserProfileImg: UserProfileImg,
    postWriter: "user1023",
    postAgo: "1시간 전",
    postViews: "50",
    postLike: "10",
  },
  {
    postId: 2,
    postTitle: "블로그 제목",
    postContent:
      "설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명",
    postBackgroundImg: PostBackground,
    postUserProfileImg: UserProfileImg,
    postWriter: "user1023",
    postAgo: "1시간 전",
    postViews: "50",
    postLike: "10",
  },
  {
    postId: 3,
    postTitle: "블로그 제목",
    postContent:
      "설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명",
    postBackgroundImg: PostBackground,
    postUserProfileImg: UserProfileImg,
    postWriter: "user1023",
    postAgo: "1시간 전",
    postViews: "50",
    postLike: "10",
  },
  {
    postId: 4,
    postTitle: "블로그 제목",
    postContent:
      "설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명",
    postBackgroundImg: PostBackground,
    postUserProfileImg: UserProfileImg,
    postWriter: "user1023",
    postAgo: "1시간 전",
    postViews: "50",
    postLike: "10",
  },
  {
    postId: 5,
    postTitle: "블로그 제목",
    postContent:
      "설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명",
    postBackgroundImg: PostBackground,
    postUserProfileImg: UserProfileImg,
    postWriter: "user1023",
    postAgo: "1시간 전",
    postViews: "50",
    postLike: "10",
  },
  {
    postId: 6,
    postTitle: "블로그 제목",
    postContent:
      "설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명",
    postBackgroundImg: PostBackground,
    postUserProfileImg: UserProfileImg,
    postWriter: "user1023",
    postAgo: "1시간 전",
    postViews: "50",
    postLike: "10",
  },
  {
    postId: 7,
    postTitle: "블로그 제목",
    postContent:
      "설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명",
    postBackgroundImg: PostBackground,
    postUserProfileImg: UserProfileImg,
    postWriter: "user1023",
    postAgo: "1시간 전",
    postViews: "50",
    postLike: "10",
  },
  {
    postId: 8,
    postTitle: "블로그 제목",
    postContent:
      "설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명",
    postBackgroundImg: PostBackground,
    postUserProfileImg: UserProfileImg,
    postWriter: "user1023",
    postAgo: "1시간 전",
    postViews: "50",
    postLike: "10",
  },
  {
    postId: 9,
    postTitle: "블로그 제목",
    postContent:
      "설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명",
    postBackgroundImg: PostBackground,
    postUserProfileImg: UserProfileImg,
    postWriter: "user1023",
    postAgo: "1시간 전",
    postViews: "50",
    postLike: "10",
  },
  {
    postId: 10,
    postTitle: "블로그 제목",
    postContent:
      "설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명",
    postBackgroundImg: PostBackground,
    postUserProfileImg: UserProfileImg,
    postWriter: "user1023",
    postAgo: "1시간 전",
    postViews: "50",
    postLike: "10",
  },
  {
    postId: 11,
    postTitle: "블로그 제목",
    postContent:
      "설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명",
    postBackgroundImg: PostBackground,
    postUserProfileImg: UserProfileImg,
    postWriter: "user1023",
    postAgo: "1시간 전",
    postViews: "50",
    postLike: "10",
  },
  {
    postId: 12,
    postTitle: "블로그 제목",
    postContent:
      "설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명",
    postBackgroundImg: PostBackground,
    postUserProfileImg: UserProfileImg,
    postWriter: "user1023",
    postAgo: "1시간 전",
    postViews: "50",
    postLike: "10",
  },
  {
    postId: 13,
    postTitle: "블로그 제목",
    postContent:
      "설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명",
    postBackgroundImg: PostBackground,
    postUserProfileImg: UserProfileImg,
    postWriter: "user1023",
    postAgo: "1시간 전",
    postViews: "50",
    postLike: "10",
  },
  {
    postId: 14,
    postTitle: "블로그 제목",
    postContent:
      "설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명",
    postBackgroundImg: PostBackground,
    postUserProfileImg: UserProfileImg,
    postWriter: "user1023",
    postAgo: "1시간 전",
    postViews: "50",
    postLike: "10",
  },
  {
    postId: 15,
    postTitle: "블로그 제목",
    postContent:
      "설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명",
    postBackgroundImg: PostBackground,
    postUserProfileImg: UserProfileImg,
    postWriter: "user1023",
    postAgo: "1시간 전",
    postViews: "50",
    postLike: "10",
  },
  {
    postId: 16,
    postTitle: "블로그 제목",
    postContent:
      "설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명",
    postBackgroundImg: PostBackground,
    postUserProfileImg: UserProfileImg,
    postWriter: "user1023",
    postAgo: "1시간 전",
    postViews: "50",
    postLike: "10",
  },
  {
    postId: 17,
    postTitle: "블로그 제목",
    postContent:
      "설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명",
    postBackgroundImg: PostBackground,
    postUserProfileImg: UserProfileImg,
    postWriter: "user1023",
    postAgo: "1시간 전",
    postViews: "50",
    postLike: "10",
  },
  {
    postId: 18,
    postTitle: "블로그 제목",
    postContent:
      "설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명",
    postBackgroundImg: PostBackground,
    postUserProfileImg: UserProfileImg,
    postWriter: "user1023",
    postAgo: "1시간 전",
    postViews: "50",
    postLike: "10",
  },
  {
    postId: 19,
    postTitle: "블로그 제목",
    postContent:
      "설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명",
    postBackgroundImg: PostBackground,
    postUserProfileImg: UserProfileImg,
    postWriter: "user1023",
    postAgo: "1시간 전",
    postViews: "50",
    postLike: "10",
  },
  {
    postId: 20,
    postTitle: "블로그 제목",
    postContent:
      "설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명",
    postBackgroundImg: PostBackground,
    postUserProfileImg: UserProfileImg,
    postWriter: "user1023",
    postAgo: "1시간 전",
    postViews: "50",
    postLike: "10",
  },
  {
    postId: 21,
    postTitle: "블로그 제목",
    postContent:
      "설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명",
    postBackgroundImg: PostBackground,
    postUserProfileImg: UserProfileImg,
    postWriter: "user1023",
    postAgo: "1시간 전",
    postViews: "50",
    postLike: "10",
  },
  {
    postId: 22,
    postTitle: "블로그 제목",
    postContent:
      "설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명",
    postBackgroundImg: PostBackground,
    postUserProfileImg: UserProfileImg,
    postWriter: "user1023",
    postAgo: "1시간 전",
    postViews: "50",
    postLike: "10",
  },
  {
    postId: 23,
    postTitle: "블로그 제목",
    postContent:
      "설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명",
    postBackgroundImg: PostBackground,
    postUserProfileImg: UserProfileImg,
    postWriter: "user1023",
    postAgo: "1시간 전",
    postViews: "50",
    postLike: "10",
  },
  {
    postId: 24,
    postTitle: "블로그 제목",
    postContent:
      "설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명",
    postBackgroundImg: PostBackground,
    postUserProfileImg: UserProfileImg,
    postWriter: "user1023",
    postAgo: "1시간 전",
    postViews: "50",
    postLike: "10",
  },
  {
    postId: 25,
    postTitle: "블로그 제목",
    postContent:
      "설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명",
    postBackgroundImg: PostBackground,
    postUserProfileImg: UserProfileImg,
    postWriter: "user1023",
    postAgo: "1시간 전",
    postViews: "50",
    postLike: "10",
  },
  {
    postId: 26,
    postTitle: "블로그 제목",
    postContent:
      "설명입니다 설명설명 설명설명입니다 설명설명 설명설명입니다 설명설명",
    postBackgroundImg: PostBackground,
    postUserProfileImg: UserProfileImg,
    postWriter: "user1023",
    postAgo: "1시간 전",
    postViews: "50",
    postLike: "10",
  },
];
