import UserProfileImg from "../../../assets/images/community/userProfile.png";

export const dummyProjectPosts = [
  {
    postId: 1,
    postState: "모집중",
    postTitle: "게시글 제목입니다",
    postContent: "게시글 내용입니다. 어쩌구 저쩌구",
    postType: "프로젝트",
    postUserProfileImg: UserProfileImg,
    postWriter: "user1023",
    postAgo: "1시간 전",
    postViews: "50",
    postLike: "30",
  },
  {
    postId: 2,
    postState: "모집완료",
    postTitle: "게시글 제목입니다",
    postContent: "게시글 내용입니다. 어쩌구 저쩌구",
    postType: "프로젝트",
    postUserProfileImg: UserProfileImg,
    postWriter: "user1023",
    postAgo: "1시간 전",
    postViews: "50",
    postLike: "30",
  },
  {
    postId: 3,
    postState: "모집중",
    postTitle: "게시글 제목입니다",
    postContent: "게시글 내용입니다. 어쩌구 저쩌구",
    postType: "프로젝트",
    postUserProfileImg: UserProfileImg,
    postWriter: "user1023",
    postAgo: "1시간 전",
    postViews: "50",
    postLike: "30",
  },
  {
    postId: 4,
    postState: "모집중",
    postTitle: "게시글 제목입니다",
    postContent: "게시글 내용입니다. 어쩌구 저쩌구",
    postType: "프로젝트",
    postUserProfileImg: UserProfileImg,
    postWriter: "user1023",
    postAgo: "1시간 전",
    postViews: "50",
    postLike: "30",
  },
  {
    postId: 5,
    postState: "모집완료",
    postTitle: "게시글 제목입니다",
    postContent: "게시글 내용입니다. 어쩌구 저쩌구",
    postType: "프로젝트",
    postUserProfileImg: UserProfileImg,
    postWriter: "user1023",
    postAgo: "1시간 전",
    postViews: "50",
    postLike: "30",
  },
  {
    postId: 6,
    postState: "모집중",
    postTitle: "게시글 제목입니다",
    postContent: "게시글 내용입니다. 어쩌구 저쩌구",
    postType: "프로젝트",
    postUserProfileImg: UserProfileImg,
    postWriter: "user1023",
    postAgo: "1시간 전",
    postViews: "50",
    postLike: "30",
  },
  {
    postId: 7,
    postState: "모집완료",
    postTitle: "게시글 제목입니다",
    postContent: "게시글 내용입니다. 어쩌구 저쩌구",
    postType: "프로젝트",
    postUserProfileImg: UserProfileImg,
    postWriter: "user1023",
    postAgo: "1시간 전",
    postViews: "50",
    postLike: "30",
  },
  {
    postId: 8,
    postState: "모집완료",
    postTitle: "게시글 제목입니다",
    postContent: "게시글 내용입니다. 어쩌구 저쩌구",
    postType: "프로젝트",
    postUserProfileImg: UserProfileImg,
    postWriter: "user1023",
    postAgo: "1시간 전",
    postViews: "50",
    postLike: "30",
  },
  {
    postId: 9,
    postState: "모집중",
    postTitle: "게시글 제목입니다",
    postContent: "게시글 내용입니다. 어쩌구 저쩌구",
    postType: "프로젝트",
    postUserProfileImg: UserProfileImg,
    postWriter: "user1023",
    postAgo: "1시간 전",
    postViews: "50",
    postLike: "30",
  },
  {
    postId: 10,
    postState: "모집중",
    postTitle: "게시글 제목입니다",
    postContent: "게시글 내용입니다. 어쩌구 저쩌구",
    postType: "프로젝트",
    postUserProfileImg: UserProfileImg,
    postWriter: "user1023",
    postAgo: "1시간 전",
    postViews: "50",
    postLike: "30",
  },
];
