import UserProfileImg from "../../../assets/images/community/userProfile.png";

export const dummyQuestionPosts = [
  {
    postId: 1,
    postState: "미완료질문",
    postTitle: "질문입니다",
    postContent: "질문 내용입니다. 어쩌구 저쩌구",
    postType: "질문",
    postUserProfileImg: UserProfileImg,
    postWriter: "user1023",
    postAgo: "1시간 전",
    postViews: "50",
    postLike: "30",
  },
  {
    postId: 2,
    postState: "미완료질문",
    postTitle: "질문입니다",
    postContent: "질문 내용입니다. 어쩌구 저쩌구",
    postType: "질문",
    postUserProfileImg: UserProfileImg,
    postWriter: "user1023",
    postAgo: "1시간 전",
    postViews: "50",
    postLike: "30",
  },
  {
    postId: 3,
    postState: "해결완료",
    postTitle: "질문입니다",
    postContent: "질문 내용입니다. 어쩌구 저쩌구",
    postType: "질문",
    postUserProfileImg: UserProfileImg,
    postWriter: "user1023",
    postAgo: "1시간 전",
    postViews: "50",
    postLike: "30",
  },
  {
    postId: 4,
    postState: "해결완료",
    postTitle: "질문입니다",
    postContent: "질문 내용입니다. 어쩌구 저쩌구",
    postType: "질문",
    postUserProfileImg: UserProfileImg,
    postWriter: "user1023",
    postAgo: "1시간 전",
    postViews: "50",
    postLike: "30",
  },
  {
    postId: 5,
    postState: "미완료질문",
    postTitle: "질문입니다",
    postContent: "질문 내용입니다. 어쩌구 저쩌구",
    postType: "질문",
    postUserProfileImg: UserProfileImg,
    postWriter: "user1023",
    postAgo: "1시간 전",
    postViews: "50",
    postLike: "30",
  },
  {
    postId: 6,
    postState: "해결완료",
    postTitle: "질문입니다",
    postContent: "질문 내용입니다. 어쩌구 저쩌구",
    postType: "질문",
    postUserProfileImg: UserProfileImg,
    postWriter: "user1023",
    postAgo: "1시간 전",
    postViews: "50",
    postLike: "30",
  },
  {
    postId: 7,
    postState: "미완료질문",
    postTitle: "질문입니다",
    postContent: "질문 내용입니다. 어쩌구 저쩌구",
    postType: "질문",
    postUserProfileImg: UserProfileImg,
    postWriter: "user1023",
    postAgo: "1시간 전",
    postViews: "50",
    postLike: "30",
  },
  {
    postId: 8,
    postState: "미완료질문",
    postTitle: "질문입니다",
    postContent: "질문 내용입니다. 어쩌구 저쩌구",
    postType: "질문",
    postUserProfileImg: UserProfileImg,
    postWriter: "user1023",
    postAgo: "1시간 전",
    postViews: "50",
    postLike: "30",
  },
  {
    postId: 9,
    postState: "해결완료",
    postTitle: "질문입니다",
    postContent: "질문 내용입니다. 어쩌구 저쩌구",
    postType: "질문",
    postUserProfileImg: UserProfileImg,
    postWriter: "user1023",
    postAgo: "1시간 전",
    postViews: "50",
    postLike: "30",
  },
  {
    postId: 10,
    postState: "미완료질문",
    postTitle: "질문입니다",
    postContent: "질문 내용입니다. 어쩌구 저쩌구",
    postType: "질문",
    postUserProfileImg: UserProfileImg,
    postWriter: "user1023",
    postAgo: "1시간 전",
    postViews: "50",
    postLike: "30",
  },
];
